### ISSUE TITLE
KeyError in Example 1

### ISSUE THREAD

**Issue by smotz9** [charman2/mesas#7]
Hey Ciaran! 

I hope all is well over there! Emilio and I have started to look into using mesas for TTD at BORR, however, while familiarizing myself with the code through your HydroLearn course I keep getting a KeyError in the first example. I'm running this in VSCode in a virtual environment I made specifically for this. Below is the error. Let me know if you need anything else. Thanks!

KeyError                                  Traceback (most recent call last)
File [~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/core/indexes/base.py:3653](https://file+.vscode-resource.vscode-cdn.net/home/samanthamotz/Documents/TTD/~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/core/indexes/base.py:3653), in Index.get_loc(self, key)
   [3652](file:///home/samanthamotz/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/core/indexes/base.py?line=3651) try:
-> [3653](file:///home/samanthamotz/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/core/indexes/base.py?line=3652)     return self._engine.get_loc(casted_key)
   [3654](file:///home/samanthamotz/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/core/indexes/base.py?line=3653) except KeyError as err:

File [~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/_libs/index.pyx:147](https://file+.vscode-resource.vscode-cdn.net/home/samanthamotz/Documents/TTD/~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/_libs/index.pyx:147), in pandas._libs.index.IndexEngine.get_loc()

File [~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/_libs/index.pyx:176](https://file+.vscode-resource.vscode-cdn.net/home/samanthamotz/Documents/TTD/~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/_libs/index.pyx:176), in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'C [conc] --> Q out [vol/time]'

The above exception was the direct cause of the following exception:

KeyError                                  Traceback (most recent call last)
[/home/samanthamotz/Documents/TTD/TTD_practice.py](https://file+.vscode-resource.vscode-cdn.net/home/samanthamotz/Documents/TTD/TTD_practice.py) in line 26
     [28](file:///home/samanthamotz/Documents/TTD/TTD_practice.py?line=27) import matplotlib.pyplot as plt
     [29](file:///home/samanthamotz/Documents/TTD/TTD_practice.py?line=28) plt.plot(data_df.index, data_df['C [conc]'])
---> [30](file:///home/samanthamotz/Documents/TTD/TTD_practice.py?line=29) plt.plot(data_df.index, data_df['C [conc] --> Q out [vol/time]'])
...
   [3658](file:///home/samanthamotz/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/core/indexes/base.py?line=3657)     #  InvalidIndexError. Otherwise we fall through and re-raise
   [3659](file:///home/samanthamotz/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/core/indexes/base.py?line=3658)     #  the TypeError.
   [3660](file:///home/samanthamotz/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/core/indexes/base.py?line=3659)     self._check_indexing_error(key)

KeyError: 'C [conc] --> Q out [vol/time]'

**Comment by charman2** [comment]
Hi! What version are you using? Use `conda list mesas` to find out.

I can't be sure unless you share the code you have, but it might be you need to do a `data_df=mymodel.data_df` to pull the updated dataframe out of the model object after it has run. If that line is missing in the tutorial I'll have to add it in.

________________________________
From: Samantha Motz ***@***.***>
Sent: Thursday, October 5, 2023 7:54:18 PM
To: charman2/mesas ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [charman2/mesas] KeyError in Example 1 (Issue #7)


Hey Ciaran!

I hope all is well over there! Emilio and I have started to look into using mesas for TTD at BORR, however, while familiarizing myself with the code through your HydroLearn course I keep getting a KeyError in the first example. I'm running this in VSCode in a virtual environment I made specifically for this. Below is the error. Let me know if you need anything else. Thanks!

KeyError Traceback (most recent call last)
File ~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/core/indexes/base.py:3653<https://file+.vscode-resource.vscode-cdn.net/home/samanthamotz/Documents/TTD/~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/core/indexes/base.py:3653>, in Index.get_loc(self, key)
3652 try:
-> 3653 return self._engine.get_loc(casted_key)
3654 except KeyError as err:

File ~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/_libs/index.pyx:147<https://file+.vscode-resource.vscode-cdn.net/home/samanthamotz/Documents/TTD/~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/_libs/index.pyx:147>, in pandas._libs.index.IndexEngine.get_loc()

File ~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/_libs/index.pyx:176<https://file+.vscode-resource.vscode-cdn.net/home/samanthamotz/Documents/TTD/~/anaconda3/envs/mesas-env/lib/python3.11/site-packages/pandas/_libs/index.pyx:176>, in pandas._libs.index.IndexEngine.get_loc()

File pandas/_libs/hashtable_class_helper.pxi:7080, in pandas._libs.hashtable.PyObjectHashTable.get_item()

File pandas/_libs/hashtable_class_helper.pxi:7088, in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'C [conc] --> Q out [vol/time]'

The above exception was the direct cause of the following exception:

KeyError Traceback (most recent call last)
/home/samanthamotz/Documents/TTD/TTD_practice.py<https://file+.vscode-resource.vscode-cdn.net/home/samanthamotz/Documents/TTD/TTD_practice.py> in line 26
28 import matplotlib.pyplot as plt
29 plt.plot(data_df.index, data_df['C [conc]'])
---> 30 plt.plot(data_df.index, data_df['C [conc] --> Q out [vol/time]'])
...
3658 # InvalidIndexError. Otherwise we fall through and re-raise
3659 # the TypeError.
3660 self._check_indexing_error(key)

KeyError: 'C [conc] --> Q out [vol/time]'

**Comment by smotz9** [comment]
I'm using version 1.20230728. But you were right! The tutorial is missing that line, I updated it in my code and there are no issues. Thanks!

**Comment by charman2** [comment]
@smotz9 can you confirm that I've fixed the Hydrolearn tutorial in the place you were seeing the problem? If not, can you pinpoint where it is?

**Comment by smotz9** [comment]
The tutorial is fixed now. I'll review the rest of the course and let you
know if I find anything else. I did see that in section 1.2 in the quiz on
the last problem the answer is C & D. The response feedback shows it's
correct, but the indicators on the selection say it's wrong. Thank you
again!
